Feature/feed
yevhentretiakov/Posts pull request #1
Opened 2022-09-07 10:45 UTC by yevhentretiakov

Developed app feed.

2022-09-07 13:47 UTC, Nikitax23 requested changes
очень много вопросов.

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Extensions/Date+Extensions.swift
> +        let formatter = DateFormatter()
название не информативное. 
можно же назвать `dateString`
`func dateString(in format: String = "defaultFormatValue") -> String`

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Extensions/Date+Extensions.swift
> +extension Date {
`DateFormatter`
рекомендуется иметь одного дейт форматтера в приватной статике. дабы не создавать один и тот же объект много раз.

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Extensions/Int+Extensions.swift
> +    var date: Date {
1) лучше так не делать. у инта не должно быть понимания о какой-то там дате))) лучше это вынести в `extension Date ` статической функцией, которая будет принимать TimeInterval (Double) , как параметр. 

2) почему именно `NSDate` ? нам не нужно сюда тянуть `Objective-C`-шный тип данных, если наш умеет то же самое. 

`Date(timeIntervalSince1970:)`

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Extensions/String+Extensions.swift
> +    func getFrameRect(withFont font: UIFont = UIFont.systemFont(ofSize: 17), width: CGFloat, lines: Int) -> CGRect {
можно просто `getRect`
Frame и так возвращает `CGRect` :D

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Extensions/UIView+Extensions.swift
> +        set {
`masksToBounds` забыл

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Services/NetworkService/NetworkService.swift
> +protocol NetworkService {
я почему-то не совсем вижу смысл в таком нетворк сервисе) 
куда делся `endPoint`? куда делся возвращаемый тип, и комлпишн клоужер? 
параметры? енкодинг? где всё? никакого смысла нет в таком сервисе, который просто получает уже готовый урл и генерит риквест

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Services/BaseRouter/BaseRouter.swift
> +
забыл марку для приватных методов

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/Model/PostModel.swift
> +        case previewText = "preview_text"
можно сделать так, а можно задать нужное свойство Decoder-y , и оно будет само конвертировать из snack case в нужный нам)

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/Model/PostModel.swift
> +    var isExpanded: Bool? = false
не нужно делать `Bool` опциональным, и задавать ему тут же значение. 
Если он у тебя не парсится, значит он здесь и не нужен) 
значит можно разделить это на `NetworkModel` и `UIModel` )

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/NetworkService/FeedNetworkService.swift
> +protocol FeedNetworkService {
дело в том, что это не совсем нетворк сервис. или даже совсем не нетворк сервис) 
он владеет свойством нетворк сервис, но сам им не является)

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/NetworkService/FeedNetworkService.swift
> +    private let networkService = DefaultNetworkService()
вот это лучше вынести в инициализатор, и дефолтным значением отдать туда наш `DefaultNetworkService()`
а само свойство должно быть типа `NetworkService`

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/NetworkService/FeedNetworkService.swift
> +        networkService.request(with: "https://raw.githubusercontent.com/anton-natife/jsons/master/api/main.json").responseDecodable(of: PostsResponse.self) { response in
1) у тебя должен быть `baseUrl` и туда должно быть вынесено `https://raw.githubusercontent.com/anton-natife/jsons/master/api`. остальное - уже эндпоинты. 
в этом сервисе можно построить ендпоинт, на основе параметров, входящих в функцию (если они есть), либо просто ендпоинт. и его уже передать в `networkService`
2) ГДЕ ЭНДПОИНТЫ? я же тебе говоирил подумать, как это с аламофаером подружить. ты в итоге сделал вообще непонятно что с аламофаером, и совсем отказался от эндпоинтов. 

Нужен будет созвон на эту тему - говори

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/NetworkService/FeedNetworkService.swift
> +                }
а что, если не будет ни ошибки, ни постов? 
ничего. тот, кто запрашивал эти данные, никогда не получит ответ. потому что ты этот кейс не обработал.

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/Presenter/FeedPresenter.swift
> +    func reloadTableView()
`reloadTableView`
презентер не знает, что там у вью. 
таблица, или коллекция, или стек, или вообще ничего. 
это означает, что здесь мы не должны упоминать `TableView`

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/Presenter/FeedPresenter.swift
> +    func presentAlert(title: String, message: String)
`presentAlert`
`presenter` не знает, каким образом `view` покажет ошибку. 
будет это алерт , или тост, или попап. 
нужно просто сказать `"showMessage"` / `"showError"` . и всё

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/Presenter/FeedPresenter.swift
> +    func sortByDate()
`sortByDate` , `sortByLikes`
метод сортировки должен быть один виден из-вне. 
ты должен вызывать `sortList(by sortType: SortType)`
и потом в презентере внутри этого метода `sortList(by:) ` ты `switch`-ом смотришь: какой тип сортировки у тебя есть , и тогда уже сортируешь так, как тебе надо

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/View/FeedViewController.swift
> +    var presenter: FeedPresenter?
а почему презентер опционал? без презентера наша вью ничего не сможет

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/View/FeedViewController.swift
> +    var presenter: FeedPresenter?
только делаешь себе проблему , что везде теперь приходится разворачивать этот презентер

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +    @IBOutlet weak var toggleButton: UIButton!
аутлет должен быть приватным

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +    @IBOutlet weak var toogleButtonTopAnchor: NSLayoutConstraint!
и здесь

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/View/FeedViewController.swift
> +            cell.toggleButton.tag = indexPath.row
здесь не должно быть никаких тегов и добавления таргетов. 
здесь должен быть клоужер или делегат (я бы предпочел клоужер), который ты передашь из презентера. и презентер сделает всё то же самое

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        date.text = model.timeshamp.date.extract("dd MMMM")
`"dd MMMM"` - формат можно спрятать в дефолтное значение (я писал коммент в экстеншне)

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +    func configure(with model: PostModel, width: CGFloat) {
какая ширина? почему ты передаешь ширину? никто не должен влиять напрямую на твои UI элементы из-вне!

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        let labelWidth = width - contentInset
не должно здесь быть никакой ширины. привязал кнопку фиксированно и всё. 
ширину лейблы можно получить и по-другому! 
высоту текста и количество линий текста можно получить и по-другому. 
не нужно ради этого такие костыли вставлять

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        toggleButtonBottomAnchor.constant = 0
1) по-моему, достаточно просто высоту убрать до 0 и на этом всё. 
2) здесь было бы удобно использовать вертикальный стек вью. но тут уж смотри сам

2022-09-07 13:47 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        if let isExpanded = model.isExpanded, isExpanded {
вот эти вещи лучше вынести в метод `setState(_ state: PostCellState)`, где у тебя будет енам: collapsed, expanded .

2022-09-08 12:00 UTC, yevhentretiakov commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        let labelWidth = width - contentInset
1) А как получить ширину лейбла по другому? 
- Пробовал получать ширину лейбла внутри `configure` просто как `previewText.bounds.width ` возвращало ширину из xib. 
- Пробовал получать внутри `layoutSubviews()` и выдавало что то ближе, но не то и с отображением баг возникал, если засовывал метод `setupToggleButton(with: previewText.bounds.width)` в `layoutSubviews()`

2) А как получить по другому количество линий и высоту текста?
- Пробовал опять же в `layoutSubviews` получать, но не корректно получало и отображало ячейки

2022-09-08 15:52 UTC, Nikitax23 requested changes
по нетворк слою надо будет созвониться

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        let labelWidth = width - contentInset
1) ширину лейбла можно получить с помощью `sizeThatFits` метода. Но уже должен быть текст задан тогда здесь. 
2) ты можешь в конце концов получить здесь ширину ячейки, если это не подходит, но зачем тянуть это из вью контроллера? 

3) есть такой метод **boundingRect** у `NSAttributedString`. Только нужно же шрифт передать тогда.

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Extensions/Date+Extensions.swift
> +    static func getDate(with interval: Double) -> Date {
`static func getDate(from timeInterval: Double)`

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Extensions/String+Extensions.swift
> +    func getRect(withFont font: UIFont = UIFont.systemFont(ofSize: 17), width: CGFloat, lines: Int) -> CGRect {
`func getRect(withFont font: UIFont = UIFont.systemFont(ofSize: 17), width: CGFloat, lines: Int)`
=> 
`func getRect(font: UIFont = UIFont.systemFont(ofSize: 17), width: CGFloat, lines: Int)`

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +    case expanded = "Expand"
```
case collapsed = "Collapse"
    case expanded = "Expand"
```

здесь лучше добавить свойство у энама `var title`, которое будет возвращаться , в зависимости от кейса энама

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +    private let textLinesLimiter = 2
`textLinesLimiter`

почему `limiter`, а не `limit` ?

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        if model.isExpanded {
тут непринципиально, но можно `setState(model.isExpanded ? .expanded : .collapsed)`

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        likesCount.text = String(model.likesCount)
`String(model.likesCount)`

кастинг типа данных следует вынести в экстеншн. 
чтоб ты у инта мог вызвать `myNumber.stringValue` или `myNumber.stringValue()`

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +    var toggleButtonAction: EmptyBlock?
думаю, что клоужер тоже следует сделать приватным и вынести его инициализацию в configure метод.

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +    @IBOutlet private weak var previewText: UILabel!
```
@IBOutlet private weak var title: UILabel!
    @IBOutlet private weak var previewText: UILabel!
    @IBOutlet private weak var likesCount: UILabel!
    @IBOutlet private weak var date: UILabel!
```

следует называть, каким элементом это является 
```
titleLabel
previewTextLabe
``` 


и тд

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/NetworkService/FeedNetworkService.swift
> +                    completion(.success(response.value?.posts ?? [PostNetworkModel]()))
`completion(.success(response.value?.posts ?? [PostNetworkModel]()))`
лучше здесь в клоужере возвращать опциональную модель.

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/View/FeedViewController.swift
> +        cell.toggleButtonAction = { [unowned self] in
почему здесь решил именно `unowned`?

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Services/NetworkService/ApiEndpoint.swift
> +            let baseURL = "https://raw.githubusercontent.com/anton-natife/jsons/master/api"
`baseURL`
у нас же здесь будет один для всех запросов )) 
почему он у тебя в кейсе объявлен? 
к нему должны иметь доступ все эндпоинты

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Services/NetworkService/ApiEndpoint.swift
> +            return baseURL + path
path должен определяться, в зависимости от self , от кейса

2022-09-08 15:52 UTC, Nikitax23 commented on Posts/Posts/Services/NetworkService/NetworkService.swift
> +    func request(_ endpoint: ApiEndpoint) -> DataRequest {
тут не должен возвращаться request. 
тут должен возвращаться ответ. Он должен возвращаться в клоужере.

2022-09-09 07:57 UTC, yevhentretiakov commented on Posts/Posts/Modules/Feed/View/FeedViewController.swift
> +        cell.toggleButtonAction = { [unowned self] in
Потому что когда будет нажатие по кнопке, вью контроллер будет в любом случае существовать, на нем же эти кнопки и отображаются

2022-09-09 09:00 UTC, yevhentretiakov commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        let labelWidth = width - contentInset
1-2. Корректную ширину и ячейки и лейбла дает получить только внутри `layoutSubviews()`. Но если отталкиваться от `layoutSubviews()` то нужно переносить туда `setupToggleButton(with: previewTextLabel.bounds.width)`, если делаю так то появляется пробел на месте скрытой кнопки. Если проскролить вверх-вниз то этот пробел уходит и становиться как надо. 

![Simulator Screen Shot - iPhone 12 mini - 2022-09-09 at 11 25 35](https://user-images.githubusercontent.com/93151033/189308493-c3dc23ec-6858-40fc-9aa8-c4902d022b8b.png)

2022-09-09 09:04 UTC, yevhentretiakov commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        let labelWidth = width - contentInset
Пробовал по всякому убрать это пустое пространство, `layoutIfNeeded`, `layoutSubviews` ,...., ничего не помогло. 

Вот предлагают тоже ширину передавать https://stackoverflow.com/questions/55387920/uitableviewcell-constraint-updates-only-happening-after-scrolling

Еще видел предлагали передавать дополнительный клоужер в ячейку и потом через него делать `reloadRowsAtIndexPaths`

2022-09-09 09:17 UTC, yevhentretiakov commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        let labelWidth = width - contentInset
3. Через boundingRect как я понял нельзя же получить CGRect для определенного количества строк чтобы потом можно было сравнить с полным размером?

2022-09-09 10:19 UTC, yevhentretiakov commented on Posts/Posts/Services/NetworkService/ApiEndpoint.swift
> +            let baseURL = "https://raw.githubusercontent.com/anton-natife/jsons/master/api"
А если разный использовался бы, то как тогда было? А где хранить правильно этот baseURL, создать структуру APIUrl и там сделать статикой baseURL?

2022-09-09 10:38 UTC, yevhentretiakov commented on Posts/Posts/Services/NetworkService/ApiEndpoint.swift
> +            return baseURL + path
Так он же сейчас и так определяется в зависимости от кейса селф, если `case .fetchPosts:` то `path = "/main.json"`

Или ты о том, что нужно чтобы вот так передавалось `.fetchPosts("/main.json")` , как в том примере что ты показывал. 

Я понимаю когда передаются какие то доп параметры, которые потом интегрируются в path `.fetchPosts(param: "param")` => `let path = "/main.json?param=\(param)"`. Апи, ссылки могут меняться и нужно будет заменить только в одном месте этот path и расставить внутри параметры, которые передают.

Но не понимаю передачу просто части ссылки. К примеру в 10 местах будет вызов  `.fetchPosts("/main.json")`, потом ссылка поменяется или апи вообще поменяется и везде нужно будет исправлять + разработчику нужно знать какие там пути к апи сервисам и даже зная можно допустить ошибку при заполнении. 

Или не о том речь?

2022-09-09 12:35 UTC, Nikitax23 commented on Posts/Posts/Services/NetworkService/ApiEndpoint.swift
> +            return baseURL + path
не о том. 

нужно просто вынести computed property 

var path: String {
switch self {
case .fetchPosts: 
return "main"
}
}

"/" можно добавить в `baseUrl` : `"https://raw.githubusercontent.com/anton-natife/jsons/master/api/"` , `.json` - это по сути расширение файла, и его можно добавить в конце там, где ты будешь билдить твой урл. он везде будет одинаковый . 

а обращаться ты будешь просто : 

`feedService.fetchPosts(someParametersIfNeeded:)`

а внутри сервиса уже будет такое: 

```
func fetchPosts(someParametersIfNeeded: SomeType) {
networkService.request(endPoint: .fetchPosts(someParametersIfNeeded)) {...} 
}
```

а уже полный урл ты получишь из `Endpoint`. 
может быть какой-то метод, который билдит рул, на основе ендпоинта и параметров.

2022-09-09 12:46 UTC, Nikitax23 commented on Posts/Posts/Modules/Feed/CustomUI/PostTableViewCell.swift
> +        let labelWidth = width - contentInset
1) тебе по сути нужно получить количество линий текста и сравнить с нашей цифрой 2 . это можно сделать через boundingRect, если нам известна ширина и шрифт. 

2) чтоб убрать видимость кнопки - достаточно установить констрейнт высоты в нулевой и применить обновление этого констрейнта. Так же, нужно учитывать, что есть переиспользование ячеек. и нужно это сетапить в дефолтный стейт, в конфигуре ячейки, в самом начале. 

лучше всего тут бы подошел конечно vertical UIStackView, и там можно просто хайдить сабвью, и она будет автоматически менять размер стек вью , с учетом того, что элемент отображать не нужно.

2022-09-09 13:04 UTC, Nikitax23 requested changes

2022-09-09 13:04 UTC, Nikitax23 commented on Posts/Posts/Services/NetworkService/NetworkService.swift
> +    func get<T: Decodable>(_ type: T.Type, from endpoint: ApiEndpoint, completion: @escaping AFResponse<T>) {
смотри. 
у тебя здесь используется по дефолту http метод `GET` . 
я хочу, чтоб твой нетворк сервис умел отправлять любые виды запросов, и любым видом `Encoding`-a , с любыми параметрами и тд. 
параметры могут сами подставляться в `query/body` параметры , в зависимости от енкодинга.

2022-09-12 10:49 UTC, anton-natife commented on Posts/Posts/Application/SceneDelegate.swift
> +    }
все неиспользуемые методы можно удалять. Проще будет читать код и меньше мусора

2022-09-12 11:05 UTC, anton-natife commented on Posts/Posts/Extensions/String+Extensions.swift
> +        return label.frame
в чем необходимость создавать тут новую лейблу ? не факт что так ты всегда получишь реальную высоту текста. Если уж нужно очень посчитать высоту, попробуй boundingRect вместо этого

2022-09-12 15:15 UTC, merged